version: 0.2

env:
  variables:
    DATABASE_URL: 'postgresql://derick:drck1089@aa1vzamu6g6a0eq.cd5bvs8hmlav.us-east-1.rds.amazonaws.com:5432/myfdb?schema=default'

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - npx prisma generate
      - npx prisma migrate deploy
      - cp package.json -r prisma .npmrc build
artifacts:
  files:
    - build/**/*
  discard-paths: no
