version: "3.9"
services:
  backend:
    build: .
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 0101
      POSTGRES_USER: murasaki
      POSTGRES_DB: myfdb
    
